### ISSUE TITLE
sumstats.py clump

### ISSUE THREAD

**Issue by yunhanch** [precimed/python_convert#36]
I compared the INDEP_BP, INDEP_SNP, LEAD_SNP, BP 4 columns in the output of cond.result.clump.indep.csv
when INDEP_SNP == LEAD_SNP,  then BP ==  INDEP_BP, which is correct.
However, when INDEP_SNP != LEAD_SNP, still BP ==  INDEP_BP, which is wrong.
Therefore, the values of BP column need to be updated.

For instance, if you look at the last two lines as shown below:
In the first line, the LEAD_SNP != INDEP_SNP, However the BP == INDEP_BP, which is wrong
In the second line, the LEAD_SNP == INDEP_SNP, so the BP == INDEP_BP, which is correct.​

36      22      **41127062        rs35860575**      1.0     **rs103197**        22      **41127062**        T       C       0.00858476471670625

36      22      **41256802        rs103197**        1.0     **rs103197**        22      **41256802**        A       G       0.0003706890734003796

**Comment by ofrei** [comment]
@yunhanch Thanks! I see the problem, will fix.

**Comment by ofrei** [comment]
Looking closer at what the scripts do, I think it's BP columns in the ``.indep.csv`` table are redundant (and same for ``.snps.csv`` table). Same for CHR column - the indep and snps files have them twice. I consider removing BP column and the second CHR column  - do you think this would be reasonable?  If for some reason it's important to have LEAD_BP and INDEP_BP in one table I think it easy to merge the ``indep`` and ``lead`` tables on LEAD_BP rs# in R, or python pandas.
 
Currently the columns are as follows:
```
$head cond.result.clump.loci.csv -n 1 | column -t
locusnum  CHR  LEAD_SNP  LEAD_BP  MinBP  MaxBP  FDR

$head cond.result.clump.lead.csv -n 1 | column -t
locusnum  CHR  LEAD_SNP  LEAD_BP  MinBP  MaxBP  FDR  is_locus_lead

$ head cond.result.clump.indep.csv -n 1 | column -t
locusnum  CHR  INDEP_BP  INDEP_SNP  R2  LEAD_SNP  CHR  BP  A1  A2  FDR

$ head cond.result.clump.snps.csv -n 1 | column -t
locusnum  CHR  INDEP_BP  INDEP_SNP  CAND_BP  CAND_SNP  R2  LEAD_SNP  CHR  BP  A1  A2  FDR
```

**Comment by scimerc** [comment]
I think you can proceed. these files are mostly used internally anyway, aren't they?

**Comment by yunhanch** [comment]
Yes, I agree with you, good to remove the CHR and the BP columns from both the indep and snp files, as the BP column is not correct for both files.

**Comment by ofrei** [comment]
Done, it should be fixed now in the master branch.

**Comment by yunhanch** [comment]
Yes, works now, thanks.
