### ISSUE TITLE
Broken Pipe

### ISSUE THREAD

**Issue by ggittu** [precimed/python_convert#43]
@ofrei  Broken pipe when running examples from Mixer 
***********************************************************************
* sumstats.py: utilities for GWAS summary statistics
* Version 1.0.0
* (C) 2016-2018 Oleksandr Frei and Alexey A. Shadrin
* Norwegian Centre for Mental Disorders Research / University of Oslo
* GNU General Public License v3
***********************************************************************
Call: 
./sumstats.py qc \
	--exclude-ranges ['6:26000000-34000000'] \
	--max-or 1e+37 

Beginning analysis at Wed Sep 30 16:56:38 2020 by gzgeorge, host fc-038
Reading sumstats file <_io.TextIOWrapper name='<stdin>' mode='r' encoding='ISO-8859-1'>...
Exclude range: chromosome 6 from BP 26000000 to 34000000
Sumstats file contains 15358497 markers.
Drop 0 markers (missing values in either of '['CHR', 'BP', 'CHR', 'BP']' columns)
Set column CHR dtype to <class 'int'>
Drop 0 markers (dtype conversion in CHR column)
Set column BP dtype to <class 'int'>
Drop 0 markers (dtype conversion in BP column)
Set column OR dtype to <class 'float'>
Drop 91255 markers (exclude range 6:26000000-34000000)
Drop 5002 markers (OR exceeded threshold 1e+37)
Traceback (most recent call last):
  File "/homes/gzgeorge/mixerexamplefiles/sumstats.py", line 2212, in <module>
    args.func(args, log)
  File "/homes/gzgeorge/mixerexamplefiles/sumstats.py", line 901, in make_qc
    fix_columns_order(sumstats).to_csv(args.out, index=False, header=True, sep='\t', na_rep='NA')
  File "/homes/gzgeorge/python3/lib/python3.6/site-packages/pandas/core/generic.py", line 3167, in to_csv
    formatter.save()
  File "/homes/gzgeorge/python3/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 206, in save
    self._save()
  File "/homes/gzgeorge/python3/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 328, in _save
    self._save_chunk(start_i, end_i)
  File "/homes/gzgeorge/python3/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 362, in _save_chunk
    libwriters.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)
  File "pandas/_libs/writers.pyx", line 70, in pandas._libs.writers.write_csv_rows
BrokenPipeError: [Errno 32] Broken pipe

Analysis finished at Wed Sep 30 17:05:02 2020
Total time elapsed: 8.0m:23.230000000000018s
Traceback (most recent call last):
  File "/homes/gzgeorge/mixerexamplefiles/sumstats.py", line 2212, in <module>
    args.func(args, log)
  File "/homes/gzgeorge/mixerexamplefiles/sumstats.py", line 901, in make_qc
    fix_columns_order(sumstats).to_csv(args.out, index=False, header=True, sep='\t', na_rep='NA')
  File "/homes/gzgeorge/python3/lib/python3.6/site-packages/pandas/core/generic.py", line 3167, in to_csv
    formatter.save()
  File "/homes/gzgeorge/python3/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 206, in save
    self._save()
  File "/homes/gzgeorge/python3/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 328, in _save
    self._save_chunk(start_i, end_i)
  File "/homes/gzgeorge/python3/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 362, in _save_chunk
    libwriters.write_csv_rows(self.data, ix, self.nlevels, self.cols, self.writer)
  File "pandas/_libs/writers.pyx", line 70, in pandas._libs.writers.write_csv_rows
BrokenPipeError: [Errno 32] Broken pipe
gzip: /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR_qc_noMHC.csv: No such file or directory
-bash-4.1$ cat mixerexamplefiles/mixerprepare.sh 
/homes/gzgeorge/python3/bin/python3 /homes/gzgeorge/mixerexamplefiles/sumstats.py zscore --sumstats /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR.csv | \
/homes/gzgeorge/python3/bin/python3 /homes/gzgeorge/mixerexamplefiles/sumstats.py qc --exclude-ranges 6:26000000-34000000 --max-or 1e37 | \
/homes/gzgeorge/python3/bin/python3 /homes/gzgeorge/mixerexamplefiles/sumstats.py neff --drop --factor 4 --out /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR_qc_noMHC.csv --force 
gzip /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR_qc_noMHC.csv

**Comment by ofrei** [comment]
@ggittu Please try to split the "pipe" into three separate calls like this, and let me know if any of the steps still crash.
```
python sumstats.py zscore --sumstats PGC_SCZ_2014_EUR.csv --out  PGC_SCZ_2014_EUR.zscore.csv 
python sumstats.py qc --sumstats PGC_SCZ_2014_EUR.zscore.csv --exclude-ranges 6:26000000-34000000 --max-or 1e37 --out PGC_SCZ_2014_EUR.qc.csv 
python sumstats.py neff --sumstats PGC_SCZ_2014_EUR.qc.csv   --drop --factor 4 --out PGC_SCZ_2014_EUR_qc_noMHC.csv --force 
```

**Comment by ggittu** [comment]
@ofrei thanks Oleksandr. seperated it out. 

/homes/gzgeorge/python3/bin/python3 /homes/gzgeorge/mixerexamplefiles/sumstats.py zscore --sumstats /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR.csv --out /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR_qc_noMHCinter1.csv
/homes/gzgeorge/python3/bin/python3 /homes/gzgeorge/mixerexamplefiles/sumstats.py qc  --sumstats /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR_qc_noMHCinter1.csv --exclude-ranges 6:26000000-34000000 --max-or 1e37 --out /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR_qc_noMHCinter2.csv
/homes/gzgeorge/python3/bin/python3 /homes/gzgeorge/mixerexamplefiles/sumstats.py neff --sumstats /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR_qc_noMHCinter2.csv --drop --factor 4 --out /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR_qc_noMHC.csv --force 

But now this is the error . WITH THE LAST COMMAND
***********************************************************************
* sumstats.py: utilities for GWAS summary statistics
* Version 1.0.0
* (C) 2016-2018 Oleksandr Frei and Alexey A. Shadrin
* Norwegian Centre for Mental Disorders Research / University of Oslo
* GNU General Public License v3
***********************************************************************
Call: 
./sumstats.py neff \
	--sumstats /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR_qc_noMHCinter2.csv \
	--out /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR_qc_noMHC.csv \
	--force  \
	--drop  

Beginning analysis at Wed Sep 30 18:07:26 2020 by gzgeorge, host fc-037
Reading summary statistics file /homes/gzgeorge/mixerexamplefiles/PGC_SCZ_2014_EUR_qc_noMHCinter2.csv...
Traceback (most recent call last):
  File "/homes/gzgeorge/mixerexamplefiles/sumstats.py", line 2212, in <module>
    args.func(args, log)
  File "/homes/gzgeorge/mixerexamplefiles/sumstats.py", line 2066, in make_neff
    df = pd.read_table(args.sumstats, delim_whitespace=True)
  File "/homes/gzgeorge/python3/lib/python3.6/site-packages/pandas/io/parsers.py", line 755, in read_table
    return read_csv(**locals())
  File "/homes/gzgeorge/python3/lib/python3.6/site-packages/pandas/io/parsers.py", line 625, in read_csv
    "Specified a delimiter with both sep and "
ValueError: Specified a delimiter with both sep and delim_whitespace=True; you can only specify one.

Analysis finished at Wed Sep 30 18:07:26 2020
Total time elapsed: 0.03s
Traceback (most recent call last):
  File "/homes/gzgeorge/mixerexamplefiles/sumstats.py", line 2212, in <module>
    args.func(args, log)
  File "/homes/gzgeorge/mixerexamplefiles/sumstats.py", line 2066, in make_neff
    df = pd.read_table(args.sumstats, delim_whitespace=True)
  File "/homes/gzgeorge/python3/lib/python3.6/site-packages/pandas/io/parsers.py", line 755, in read_table
    return read_csv(**locals())
  File "/homes/gzgeorge/python3/lib/python3.6/site-packages/pandas/io/parsers.py", line 625, in read_csv
    "Specified a delimiter with both sep and "
ValueError: Specified a delimiter with both sep and delim_whitespace=True; you can only specify one.

**Comment by ofrei** [comment]
Thanks, that's a real error I need to fix:
>ValueError: Specified a delimiter with both sep and delim_whitespace=True; you can only specify one.
What's your python version? I guess very recent . Previously pd.read_table  issued a warning that it will soon be deprecated - perhaps it's time for me to switch all read_table calls with read_csv, as suggested by python pandas library a while ago.
I'll try to fix tomorrow.

**Comment by ggittu** [comment]
@ofrei thank you. looking forward to it. We are using python 3.6

**Comment by ofrei** [comment]
@ggittu I've replaced all "read_table" with "read_csv", could you please "git pull" the latest version from python_convert repo, and try again?
So far I haven't managed to reproduce your error, but with ``read_table`` I get this warning:
```
sumstats.py:2066: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  df = pd.read_table(args.sumstats, delim_whitespace=True)
```
It seem related to your problem, and it's gone with ``read_csv``, so I hope this may solve the problem.

**Comment by ggittu** [comment]
Perfect! This fix helped. Able to run. Thanks @ofrei
