### ISSUE TITLE
sumstats.py creates indep.csv file with all R2=1.0

### ISSUE THREAD

**Issue by EPTissink** [precimed/python_convert#51]
I have used sumstats.py to clump conjFDR output to define loci, lead, independent and candidate SNPs. (All sumstats and reference panel were EUR) The independent SNPs are supposed to be independent from each other (R2<0.6) and from the lead SNPs, but all lines of the indep.csv file include an R2 value of 1.0. When manually checking the R2 online, the SNPs are indeed independent, so the R2=1.0 values may be a bug?

In this example, the actual R2 value between rs73209865 and rs77060135 is around 0.2

```
locusnum        CHR     INDEP_BP        INDEP_SNP       R2      LEAD_SNP        A1      A2      FDR
1       4       896163  rs73209865      1.0     rs77060135      T       C       0.0014758958454633
```

**Comment by ofrei** [comment]
@EPTissink thanks for reporting. Sounds weird, I'll have a look

**Comment by ofrei** [comment]
@EPTissink Indeed this is a bug in  'sumstats.py clump' related to how it generates ``<out>.indep.csv`` file. Right now this file will always contain 1 in R2 column, for all SNPs. This however does not affect the way indep, loci and candidate SNPs are generated, so it's only a visualisation issue.

 I suggest to remove "R2" column from "<out>.indep.csv" file. To explain why let's go over few things.

>The independent SNPs are supposed to be independent from each other (R2<0.6) ...
This is correct

>... and from the lead SNPs
This is not correct - or at least I disagree with this. To me a Lead SNP is by definition also an Indep SNP. We start with a set of independent significant SNPs, and prune them at a more stringent threshold (R2<0.1) to define a subset that we call lead SNPs. So it's a matter of definition - it's of course possible to remove lead SNP from the list of indep significant SNPs, but to me this would only make things more obscure.

Generally it's of course possible to find the correlation between lead SNP and each independent significant SNP that is part of corresponding loci. However I currently don't make a call to plink that generates this information. The "<out>.indep.csv" is currently generated by subsetting lines from "<out>.snps.csv" which contain one entry for each candidate SNP that are in LD r2 of 0.6 or higher with one of indepedent significant SNPs. 

The list of lead SNPs is produced by clumping, so internally PLINK must have computed the LD, however it's not stored in the output files currently generated.
